
ALTER TABLE INGREDIENTS
MODIFY COLUMN NAME VARCHAR(255) NOT NULL;


ALTER TABLE INGREDIENTS
MODIFY COLUMN CONTAINS_LACTOSE BOOLEAN UNIQUE;

ALTER TABLE INGREDIENTS
MODIFY COLUMN VEGETARIAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENTS
MODIFY COLUMN VEGAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENTS
MODIFY COLUMN GLUTEN_FREE BOOLEAN UNIQUE;
