# create a new table called 'CHEAP_MEALS'
CREATE TABLE CHEAP_MEALS AS
SELECT *
FROM MEAL
WHERE PRICE < 15;

CREATE TABLE VEGAN_INGREDIENT AS
SELECT *
FROM INGREDIENT
WHERE VEGAN = TRUE;

#create a view called 'EXPENSIVE_MEAL' 
CREATE VIEW EXPENSIVE_MEAL AS
SELECT *
FROM MEAL
WHERE PRICE > 15;

#create a view called 'LACTOSE_FREE_INGREDIENT'
CREATE VIEW LACTOSE_FREE_INGREDIENT AS
SELECT *
FROM INGREDIENT
WHERE CONTAINS_LACTOSE = FALSE;

#create a new table called 'HIGH_CALORIE_MEAL' that contains all meals with more than 650 calories.
CREATE TABLE HIGH_CALORIE_MEAL AS
SELECT *
FROM MEAL
WHERE CALORIES > 650;
